### Create New User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "password":"123",
    "username":"amir"
}

### login Users
POST http://localhost:3000/auth/login
content-type: application/json

{
    "password":"123",
    "username":"amir"
}
